// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosSYAC.DataAccess;

#nullable disable

namespace PedidosSYAC.DataAccess.Migrations
{
    [DbContext(typeof(PedidosContext))]
    partial class PedidosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "DirSYAC",
                            Identificacion = "1230000007",
                            Nombre = "Jimmy"
                        });
                });

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Registrado"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Confirmar"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Anular"
                        });
                });

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("Id_Estado");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Id_Cliente = 1,
                            Id_Estado = 1,
                            ValorTotal = 210m
                        });
                });

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 25,
                            Nombre = "Magnat",
                            ValorUnitario = 50m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 25,
                            Nombre = "Code Noir",
                            ValorUnitario = 60m
                        });
                });

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.ProductosXPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPorCantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Pedido");

                    b.HasIndex("Id_Producto");

                    b.ToTable("ProductosXPedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            Id_Pedido = 1,
                            Id_Producto = 1,
                            ValorPorCantidad = 100m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            Id_Pedido = 1,
                            Id_Producto = 2,
                            ValorPorCantidad = 60m
                        });
                });

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.Pedidos", b =>
                {
                    b.HasOne("PedidosSYAC.DataAccess.Entity.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PedidosSYAC.DataAccess.Entity.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PedidosSYAC.DataAccess.Entity.ProductosXPedido", b =>
                {
                    b.HasOne("PedidosSYAC.DataAccess.Entity.Pedidos", "Pedido")
                        .WithMany()
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PedidosSYAC.DataAccess.Entity.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
